"""add insights table

Revision ID: 14fc7f6a99e3
Revises: 72bfe64b241f
Create Date: 2026-04-17 13:23:24.295778

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14fc7f6a99e3'
down_revision: Union[str, Sequence[str], None] = '72bfe64b241f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('impact_one_time_cents', sa.Integer(), nullable=False),
    sa.Column('impact_annual_cents', sa.Integer(), nullable=False),
    sa.Column('effort', sa.String(length=10), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('action_json', sa.Text(), nullable=True),
    sa.Column('related_goal_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('snoozed_until', sa.Date(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_inputs_hash', sa.String(length=64), nullable=True),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'user_id', 'engine', 'kind', 'inputs_hash', name='uq_insights_user_engine_kind_hash'
    )
    )
    op.create_index(op.f('ix_insights_user_id'), 'insights', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_user_id'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
