"""add spending_profiles recommendation_snapshots and card issuer

Revision ID: 72bfe64b241f
Revises: 24568b8e4f03
Create Date: 2026-04-12 16:45:05.147071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72bfe64b241f'
down_revision: Union[str, Sequence[str], None] = '24568b8e4f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', name='uq_recommendation_snapshots_user_type')
    )
    op.create_index(op.f('ix_recommendation_snapshots_user_id'), 'recommendation_snapshots', ['user_id'], unique=False)
    op.create_table('spending_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('avg_monthly_spend', sa.Float(), nullable=False),
    sa.Column('category_breakdown_json', sa.Text(), nullable=False),
    sa.Column('top_merchants_json', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_spending_profiles_user')
    )
    op.create_index(op.f('ix_spending_profiles_user_id'), 'spending_profiles', ['user_id'], unique=False)
    op.add_column('cards', sa.Column('issuer', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'issuer')
    op.drop_index(op.f('ix_spending_profiles_user_id'), table_name='spending_profiles')
    op.drop_table('spending_profiles')
    op.drop_index(op.f('ix_recommendation_snapshots_user_id'), table_name='recommendation_snapshots')
    op.drop_table('recommendation_snapshots')
    # ### end Alembic commands ###
